// Local build step: parses ../spreadsheet_ALL.txt and writes lib/rulebookData.js
// (an embedded module the API uses to seed the database server-side).
//   node emit_rulebook.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { splitSheets, build } from './lib/rulebookParse.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const raw = readFileSync(path.join(here, '..', 'spreadsheet_ALL.txt'), 'utf8').replace(/\r\n/g, '\n');
const categories = build(splitSheets(raw));

const out = '// AUTO-GENERATED by emit_rulebook.mjs — do not edit by hand.\n' +
  'export const RULEBOOK = ' + JSON.stringify(categories, null, 2) + ';\n';
writeFileSync(path.join(here, 'lib', 'rulebookData.js'), out);

const total = categories.reduce((n, c) => n + c.entries.length, 0);
console.log(`Wrote lib/rulebookData.js — ${categories.length} categories, ${total} entries.`);
for (const c of categories) console.log(`  ${c.name.padEnd(26)} [${c.dimension}] ${c.entries.length}`);
