// AUTO-GENERATED by emit_rulebook.mjs — do not edit by hand.
export const RULEBOOK = [
  {
    "slug": "how-to-use",
    "name": "How To Use",
    "dimension": "guide",
    "description": "How To Use This Document",
    "sort_order": 1,
    "entries": [
      {
        "label": "1. Choose Your Niche To Make 10 Designs For",
        "note": null,
        "grouping": null
      },
      {
        "label": "2. See what the niche has already for bestselling designs",
        "note": null,
        "grouping": null
      },
      {
        "label": "3. Come to this doc and choose a trending design style",
        "note": null,
        "grouping": null
      },
      {
        "label": "4. Make sure you are adding value and not just making a slight knock off of the bestseller",
        "note": null,
        "grouping": null
      },
      {
        "label": "5. Make sure you aren't just making 10 slight variations of a design, make sure to make 10 completely different designs that add value! - If you need inspiration, checking out the value add saying ideas, cross niche ideas etc. on this doc",
        "note": null,
        "grouping": null
      }
    ]
  },
  {
    "slug": "design-styles",
    "name": "Design Styles",
    "dimension": "design_style",
    "description": "Proven, trending and text-only design styles for POD apparel.",
    "sort_order": 2,
    "entries": [
      {
        "label": "Amalfi Coast Style Designs",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Every other letter a different color",
        "note": null,
        "grouping": "Text Only Design Styles"
      },
      {
        "label": "Vertical Stripe Designs",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Collegiate Text",
        "note": null,
        "grouping": "Text Only Design Styles"
      },
      {
        "label": "Bubble Pattern Font",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Text to the left",
        "note": null,
        "grouping": "Text Only Design Styles"
      },
      {
        "label": "Handdrawn Text & Doodle/Line Drawing Graphics",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Retro Wavy",
        "note": null,
        "grouping": "Text Only Design Styles"
      },
      {
        "label": "Stamp Frame",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Fake Definition",
        "note": null,
        "grouping": "Text Only Design Styles"
      },
      {
        "label": "Retro Frame",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Bold Distressed All Caps Text",
        "note": null,
        "grouping": "Text Only Design Styles"
      },
      {
        "label": "Heart Locket",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Little Frames",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Patchwork",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Ransom Note Letters",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Continuous Line Drawings",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Thank you bag text",
        "note": null,
        "grouping": "Random Design Styles"
      },
      {
        "label": "Mixed Pattern designs",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Sign Language Designs",
        "note": null,
        "grouping": "Random Design Styles"
      },
      {
        "label": "Paragraph Text With Text Over it",
        "note": null,
        "grouping": "Hot Newer Trending Design Styles"
      },
      {
        "label": "Collegiate Pattern Text",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Graphic made out of flowers",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Watercolor Graphic Designs",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Social Club",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Minimalist Text Only",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Minimalst Text With Small Graphic",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Arched Text on Back",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Big Bow Graphic",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "4 Brush Stroke Design",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Boho Floral",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Checkerboard Cut Out",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Graphic w/ text around it",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Monochrome",
        "note": null,
        "grouping": "Top Recent Proven Design Styles"
      },
      {
        "label": "Marquee Letters",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Collage of Graphics",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Tarot Card",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Graphic Alphabet",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Checkerboard Background/curved text",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Heart Designs",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Repeating Text w/ Graphic on top",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Fake Concert Tour",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Howling at the Moon",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Fake Logo",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "3-5 Graphics Across",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "3x3 Graphic Pattern",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Flowers Behind Text",
        "note": null,
        "grouping": "Longer Term Proven Design Styles"
      },
      {
        "label": "Fake Review",
        "note": null,
        "grouping": "Bootleg Design Style"
      },
      {
        "label": "Curved Text Above Graphic + Straight text Below",
        "note": null,
        "grouping": "Bootleg Design Style"
      }
    ]
  },
  {
    "slug": "trending-aesthetics",
    "name": "Trending Aesthetics",
    "dimension": "aesthetic",
    "description": "Color and visual aesthetic combinations that are currently selling.",
    "sort_order": 3,
    "entries": [
      {
        "label": "Coquette",
        "note": null,
        "grouping": null
      },
      {
        "label": "Ivory text on Light Green Comfort Colors",
        "note": null,
        "grouping": null
      },
      {
        "label": "Blue on Ivory",
        "note": null,
        "grouping": null
      },
      {
        "label": "Ivory on Brown",
        "note": null,
        "grouping": null
      },
      {
        "label": "White/Ivory shirt with Red design",
        "note": null,
        "grouping": null
      },
      {
        "label": "White/Ivory shirt with brown design",
        "note": null,
        "grouping": null
      },
      {
        "label": "Monochrome",
        "note": null,
        "grouping": null
      },
      {
        "label": "Cottagecore",
        "note": null,
        "grouping": null
      },
      {
        "label": "Celestial",
        "note": null,
        "grouping": null
      },
      {
        "label": "Brown & Leopard Print",
        "note": null,
        "grouping": null
      }
    ]
  },
  {
    "slug": "value-add-sayings",
    "name": "Value Add Sayings",
    "dimension": "phrase",
    "description": "Fill-in-the-blank saying formulas (replace ___/X/*** with the niche).",
    "sort_order": 4,
    "entries": [
      {
        "label": "Letter X is for X (For example \"L is for Love crossed out and then a different L word below\"",
        "note": null,
        "grouping": null
      },
      {
        "label": "These boots are made for “x”",
        "note": null,
        "grouping": null
      },
      {
        "label": "and she *** ever after",
        "note": null,
        "grouping": null
      },
      {
        "label": "Easy tiger did you ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "Support local *** or Support your local ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "Happiness is being a ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "I don't need therapy, I just need my ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "I just want to drink wine and ****",
        "note": null,
        "grouping": null
      },
      {
        "label": "eat sleep *** repeat",
        "note": null,
        "grouping": null
      },
      {
        "label": "Just one more *** I promise",
        "note": null,
        "grouping": null
      },
      {
        "label": "Always be yourself, except if you can be a *** then always be a *** (Animals for example)",
        "note": null,
        "grouping": null
      },
      {
        "label": "This is my **** shirt",
        "note": null,
        "grouping": null
      },
      {
        "label": "All you need is love and ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "All this girl cares about is *** and maybe 3 people",
        "note": null,
        "grouping": null
      },
      {
        "label": "My favorite season is *****",
        "note": null,
        "grouping": null
      },
      {
        "label": "Life of a *** addict",
        "note": null,
        "grouping": null
      },
      {
        "label": "Never underestimate an old man with a *** (Think a bike, skiis etc)",
        "note": null,
        "grouping": null
      },
      {
        "label": "I never dreamed I'd be a sexy *** but here I am killin it",
        "note": null,
        "grouping": null
      },
      {
        "label": "I'm silently judging your ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "It's a *** thing, you wouldn't understand",
        "note": null,
        "grouping": null
      },
      {
        "label": "100% chance of me telling you ****",
        "note": null,
        "grouping": null
      },
      {
        "label": "Nacho average ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "Dibs on the **** (Coach for example)",
        "note": null,
        "grouping": null
      },
      {
        "label": "WTF (three words that start with those letters)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Easily Distracted By...",
        "note": null,
        "grouping": null
      },
      {
        "label": "Life happens, *** helps",
        "note": null,
        "grouping": null
      },
      {
        "label": "Friends don't let friends ***",
        "note": null,
        "grouping": null
      },
      {
        "label": "Get in loser, we're ****",
        "note": null,
        "grouping": null
      },
      {
        "label": "Born to *** Forced to ****",
        "note": null,
        "grouping": null
      },
      {
        "label": "I'll be in my office (with picture/graphic of place that is not an office ex: a garden)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Hold on Partner, I'm ****",
        "note": null,
        "grouping": null
      },
      {
        "label": "Just Wingin' it 'till *** (with goose graphic)",
        "note": null,
        "grouping": null
      },
      {
        "label": "*** is my therapy",
        "note": null,
        "grouping": null
      },
      {
        "label": "*** and coffee",
        "note": null,
        "grouping": null
      },
      {
        "label": "**** is always the answer",
        "note": null,
        "grouping": null
      },
      {
        "label": "*** cheaper than therapy",
        "note": null,
        "grouping": null
      },
      {
        "label": "Life update: *** (ex: still tired)",
        "note": null,
        "grouping": null
      },
      {
        "label": "I'm a slut for **** (or *** slut)",
        "note": null,
        "grouping": null
      },
      {
        "label": "*** Very bad, would not recommend (include one star out of 5 graphic)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Will Yap About ****",
        "note": null,
        "grouping": null
      },
      {
        "label": "MILF Man I Love (Word That start with F)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Queen of *****",
        "note": null,
        "grouping": null
      },
      {
        "label": "Caution, May start talking about *** at any time",
        "note": null,
        "grouping": null
      },
      {
        "label": "Sometimes I wonder if X is thinking about me too",
        "note": null,
        "grouping": null
      },
      {
        "label": "Maybe X is addicted to me",
        "note": null,
        "grouping": null
      },
      {
        "label": "You are \"X\" \"X\" \"X\" (little graphics realted to your niche with the nice words around them)",
        "note": null,
        "grouping": null
      },
      {
        "label": "X is my Jam (optional : & I'm here to spread it)",
        "note": null,
        "grouping": null
      },
      {
        "label": "In my X era",
        "note": null,
        "grouping": null
      },
      {
        "label": "X because murder is wrong",
        "note": null,
        "grouping": null
      },
      {
        "label": "I X, What's your super power?",
        "note": null,
        "grouping": null
      },
      {
        "label": "Sorry Can't X Bye",
        "note": null,
        "grouping": null
      },
      {
        "label": "It's a good day for X (Or it's a beautiful day for X)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Never Enough X",
        "note": null,
        "grouping": null
      },
      {
        "label": "Can't talk right now, doing X stuff",
        "note": null,
        "grouping": null
      },
      {
        "label": "It's not easy being X but here I am killing it",
        "note": null,
        "grouping": null
      },
      {
        "label": "The X Whisperer",
        "note": null,
        "grouping": null
      },
      {
        "label": "Only hot bitches X",
        "note": null,
        "grouping": null
      },
      {
        "label": "I X and don't trust the government",
        "note": null,
        "grouping": null
      },
      {
        "label": "X Are like Potato Chips, You Can't Have Just One",
        "note": null,
        "grouping": null
      },
      {
        "label": "X But I'm Being Really Brave About It (My tummy hurts, I'm really cold for example)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Wait, I see ___ or Hold on, I see ___",
        "note": null,
        "grouping": null
      },
      {
        "label": "X Nerd (Bird Nerd, Dirt Nerd etc)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Personally Victimized by X",
        "note": null,
        "grouping": null
      },
      {
        "label": "Probably Thinking About X",
        "note": null,
        "grouping": null
      },
      {
        "label": "Things I do in my spare time (Show 4-6 things all related to one niche like think about X, talk about X, etc)",
        "note": null,
        "grouping": null
      },
      {
        "label": "(3 super niche realted words) If you know, you know",
        "note": null,
        "grouping": null
      },
      {
        "label": "X Dealer (Example: Treat Dealer for a dog owner)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Weekend Forecast: X",
        "note": null,
        "grouping": null
      },
      {
        "label": "I'm into Fitness, fit'ness this X into X (fit'ness deer in my freezer)",
        "note": null,
        "grouping": null
      },
      {
        "label": "A X a day keeps the X away",
        "note": null,
        "grouping": null
      },
      {
        "label": "I didn’t choose the ___ life, the ___ life chose me",
        "note": null,
        "grouping": null
      },
      {
        "label": "I’m not ___, I’m ___",
        "note": null,
        "grouping": null
      },
      {
        "label": "Powered by ___",
        "note": null,
        "grouping": null
      },
      {
        "label": "Fueled by ___",
        "note": null,
        "grouping": null
      },
      {
        "label": "Professional ___ (Professional Dog Spoiler)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Emotionally attached to ___ (Fictional characters for example)",
        "note": null,
        "grouping": null
      },
      {
        "label": "___ is my happy place",
        "note": null,
        "grouping": null
      },
      {
        "label": "Less ___, more ___ (Less people, more dogs)",
        "note": null,
        "grouping": null
      },
      {
        "label": "I’d rather be ___ (I’d rather be thrifting)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Powered by ___ + ___ or Powered By ___ (Powered by Prayer or Powered by Coffee and Jesus)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Ask me about my ___",
        "note": null,
        "grouping": null
      },
      {
        "label": "Life is better with ___ (Life it better with a dog, or two, or three)",
        "note": null,
        "grouping": null
      },
      {
        "label": "One ___ won't fix all your problems, but three might",
        "note": null,
        "grouping": null
      },
      {
        "label": "It's too ___ outside (peopley, nonfictiony)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Mentally I'm ____ (at somewhere else or doing something else)",
        "note": null,
        "grouping": null
      },
      {
        "label": "If it Involves ___ and ___ then count me in",
        "note": null,
        "grouping": null
      },
      {
        "label": "My needs are simple (3 graphics above related to your niche)",
        "note": null,
        "grouping": null
      },
      {
        "label": "You can't tell me what to do, you're not my ___ (Dog, Granddaugher etc)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Off to ___ (praise the lord, teach speech etc - ususally paird with animal on scooter)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Oops I bought more _____",
        "note": null,
        "grouping": null
      },
      {
        "label": "LOVE (But the O is something related to your niche)",
        "note": null,
        "grouping": null
      },
      {
        "label": "I lef my ____ to be here so this better be good",
        "note": null,
        "grouping": null
      },
      {
        "label": "___trovert - A person who prefers spending time ___ than with people",
        "note": null,
        "grouping": null
      },
      {
        "label": "Life isn't all ____ & ____ But it should be",
        "note": null,
        "grouping": null
      },
      {
        "label": "Apparently I like _____",
        "note": null,
        "grouping": null
      },
      {
        "label": "Cools Moms ______",
        "note": null,
        "grouping": null
      },
      {
        "label": "It's giving ______ (Like godmother, teacher etc something that they are becoming)",
        "note": null,
        "grouping": null
      },
      {
        "label": "Every Day I'm ------in (Example bestseler - Everyday I'm Motherin')",
        "note": null,
        "grouping": null
      },
      {
        "label": "Do not disturb X in progress",
        "note": null,
        "grouping": null
      },
      {
        "label": "X “trovert” (ex: Catrovert and booktrovert)",
        "note": null,
        "grouping": null
      },
      {
        "label": "On Wednesdays we X",
        "note": null,
        "grouping": null
      }
    ]
  },
  {
    "slug": "value-adds",
    "name": "Value Adds",
    "dimension": "value_add",
    "description": "Listing-level techniques that add value (matching sets, back prints, bundles, etc.).",
    "sort_order": 5,
    "entries": [
      {
        "label": "Multiple styles/sayings in one listing",
        "note": null,
        "grouping": null
      },
      {
        "label": "Showing multiple color choices in main image",
        "note": null,
        "grouping": null
      },
      {
        "label": "/ Turning into matching shirts",
        "note": null,
        "grouping": null
      },
      {
        "label": "Mommy And Me Shirts",
        "note": null,
        "grouping": null
      },
      {
        "label": "Couples Shirts",
        "note": null,
        "grouping": null
      },
      {
        "label": "Back Designs",
        "note": null,
        "grouping": null
      },
      {
        "label": "Pocket Sized Designs",
        "note": null,
        "grouping": null
      },
      {
        "label": "Group Shirts",
        "note": null,
        "grouping": null
      },
      {
        "label": "Personalized Listings",
        "note": null,
        "grouping": null
      },
      {
        "label": "Back spine/front designs",
        "note": null,
        "grouping": null
      },
      {
        "label": "Sleeve Prints",
        "note": null,
        "grouping": null
      },
      {
        "label": "Embroidery",
        "note": null,
        "grouping": null
      }
    ]
  },
  {
    "slug": "cross-niche-ideas",
    "name": "Cross Niche Ideas",
    "dimension": "cross_niche",
    "description": "Trending motifs/elements that cross over into many niches.",
    "sort_order": 6,
    "entries": [
      {
        "label": "Racoons/Possums",
        "note": null,
        "grouping": null
      },
      {
        "label": "The word 'Feral'",
        "note": null,
        "grouping": null
      },
      {
        "label": "Geese",
        "note": null,
        "grouping": null
      },
      {
        "label": "Cows",
        "note": null,
        "grouping": null
      },
      {
        "label": "Western",
        "note": null,
        "grouping": null
      },
      {
        "label": "Sasquatch",
        "note": null,
        "grouping": null
      },
      {
        "label": "Otters",
        "note": null,
        "grouping": null
      },
      {
        "label": "Coffee",
        "note": null,
        "grouping": null
      },
      {
        "label": "Mom",
        "note": null,
        "grouping": null
      },
      {
        "label": "Cats",
        "note": null,
        "grouping": null
      }
    ]
  },
  {
    "slug": "bestselling-shirt-colors",
    "name": "Bestselling Shirt Colors",
    "dimension": "color",
    "description": "Top-selling blank colors per print provider / brand.",
    "sort_order": 7,
    "entries": [
      {
        "label": "Black",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "White",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Dark Grey Heather",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Athletic Heather",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Heather Mauve",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Navy",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Natural",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Heather Navy",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Heather Peach",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Pink",
        "note": null,
        "grouping": "For Bella & Canvas 3001"
      },
      {
        "label": "Sand",
        "note": null,
        "grouping": "For the Gildan 18000"
      },
      {
        "label": "Sport Grey",
        "note": null,
        "grouping": "For the Gildan 18000"
      },
      {
        "label": "Ash",
        "note": null,
        "grouping": "For the Gildan 18000"
      },
      {
        "label": "Forest Green",
        "note": null,
        "grouping": "For the Gildan 18000"
      },
      {
        "label": "Light Pink",
        "note": null,
        "grouping": "For the Gildan 18000"
      },
      {
        "label": "Dark Heather",
        "note": null,
        "grouping": "For the Gildan 18000"
      },
      {
        "label": "Light Blue",
        "note": null,
        "grouping": "For the Gildan 18000"
      },
      {
        "label": "Pepper",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Ivory",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Moss",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Espresso",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Blue Jean",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Yam",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Bay",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Light Green",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Blue Spruce",
        "note": null,
        "grouping": "Comfort Colors C1717"
      },
      {
        "label": "Berry",
        "note": null,
        "grouping": "Comfort Colors C1717"
      }
    ]
  },
  {
    "slug": "fonts-typography",
    "name": "Fonts & Typography",
    "dimension": "font",
    "description": "Recommended fonts for text-based designs.",
    "sort_order": 8,
    "entries": [
      {
        "label": "Beth Ellen",
        "note": "Handwritten font",
        "grouping": null
      },
      {
        "label": "Special Elite",
        "note": "Great typewriter font for text only designs",
        "grouping": null
      },
      {
        "label": "Edmund Texture",
        "note": "great distressed font",
        "grouping": null
      }
    ]
  },
  {
    "slug": "design-style-tutorials",
    "name": "Design Style Tutorials",
    "dimension": "design_style",
    "description": "External tutorials/templates for specific design styles.",
    "sort_order": 9,
    "entries": [
      {
        "label": "Bootleg Design Style",
        "note": "https://www.skool.com/podroadmap/classroom/3fe2e420?md=fdb9bed5345a46adaa64833d82a5c52d",
        "grouping": null
      },
      {
        "label": "Mixed Patterns Designs",
        "note": "https://youtu.be/HFdiwe15Bn0,",
        "grouping": null
      },
      {
        "label": "Marquee Letters",
        "note": "https://www.etsy.com/listing/1522116032/marquee-alphabet-png-colorful-font?ls=a&ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=marquee+letter+font&ref=sc_gallery-1-2&pro=1&sts=1&dd=1&plkey=EuVunnwxxG8pWaZqnFkeuaMEira1%3ALTad90885bc8cde9679355de819433c75a02e54e1a",
        "grouping": null
      },
      {
        "label": "Retro Frame",
        "note": "https://youtu.be/HFdiwe15Bn0",
        "grouping": null
      },
      {
        "label": "Monochrome",
        "note": "https://www.canva.com/design/DAG2vRZMe6U/pFKJT5KwhXgVTBoIz6ezBA/view?utm_content=DAG2vRZMe6U&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview",
        "grouping": null
      },
      {
        "label": "Collegiate Pattern",
        "note": "https://www.canva.com/design/DAGdgYSXhiQ/fmp2lhd68YrY9CWIASbTZA/view?utm_content=DAGdgYSXhiQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview",
        "grouping": null
      },
      {
        "label": "Bubble Pattern Font",
        "note": "https://www.etsy.com/listing/1739764369/canva-frame-template-alphabet-o-fill,,",
        "grouping": null
      },
      {
        "label": "Big Bow Graphic",
        "note": "https://www.canva.com/design/DAGdgYSXhiQ/fmp2lhd68YrY9CWIASbTZA/view?utm_content=DAGdgYSXhiQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview",
        "grouping": null
      },
      {
        "label": "Howling At The Moon",
        "note": "https://www.skool.com/podroadmap/classroom/3fe2e420?md=0add278df153469cb3fda203ba1c9ae7",
        "grouping": null
      },
      {
        "label": "Amalfi Coast Style",
        "note": "https://www.skool.com/podroadmap/classroom/be4dd19b?md=1405a89cc644451388674a19bf52063b,",
        "grouping": null
      }
    ]
  }
];
